### ISSUE TITLE
MBVRoute collisions with CoreNavigation Route Swift class name

### ISSUE THREAD

**Issue by gduranon** [mapbox/mapbox-vision-ios#101]
## Description
As the issue title describes, MBVRoute defines Route as Swift class name. This makes impossible to use both Vision and CoreNavigation in the same app. You should assign a different Swift class name to avoid conflict.

## Configuration
 - OS: iOS
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [0.4.0]
   - MapboxVisionARNative [0.4.0]
   - MapboxVisionSafetyNative [0.4.0]
   - MapboxCoreNavigation (0.31.0)

**Comment by chezzdev** [comment]
Hello @gduranon, thanks for trying out `MapboxVision`.
Swift allows using same-name types which were defined in different modules. To use both `Route` classes in the same scope, please reference their types as `MapboxVisionARNative.Route` and `MapboxDirections.Route`.
Let me know if that worked for you.

**Comment by vladzima** [comment]
Closing this for now. Feel free to reopen if needed.
