### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by gduranon** [mapbox/mapbox-vision-ios#102]
## Description
Provided examples and documentation do not match current library methods

## Configuration
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.3.1]
   - MapboxVisionARNative [e.g. 0.3.1]
   - MapboxVisionSafetyNative [e.g. 0.3.1]

**Comment by chezzdev** [comment]
Thanks for posting the issue @gduranon.
Please refer to documentation at https://docs.mapbox.com/ios/vision/overview/ and to examples at https://docs.mapbox.com/ios/vision/examples/. They are up-to-date with version `0.3.1` and will be shortly updated for `0.4.0`. For now you may use documentation comments in the code of the frameworks.

**Comment by vladzima** [comment]
Closing this for now. Feel free to reopen if needed.
