### ISSUE TITLE
 Write unit tests for video paths in Telemetry SDK

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-vision-ios#111]
## Description
That's a part of https://github.com/mapbox/mapbox-vision/issues/1052
Linked issue: https://github.com/mapbox/mapbox-vision/issues/836

## Goal

The goal is to avoid potential issues in the future because it leads to incorrect values in analytics.

## Steps
TBD

**Comment by chezzdev** [comment]
Irrelevant due to internal changes in synchronization.
