### ISSUE TITLE
Allow to apply actual state of ARCamera (from core) during the AR scene's rendering process

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-vision-ios#119]
## Description

Current version of `ARRenderer: MTKViewDelegate` doesn't have specific implementation to update `ARCamera`'s state from core (method `mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize)` is empty).
As it was discussed with @deniskoronchik we should implement support, (additionally refactor `ARCameraNode`'s logic based on work done in #118 )

## Goal

It will allow us to have an ability to apply ARCamera's changes from core and to have clear structure of AR-related types.

## Steps
- [ ] Refactor `ARCameraNode`
- [ ] Implement method in `MTKViewDelegate`
- [ ] Write unit tests
- [ ] Tested and acceptance criteria is matched (result matches the goal)

**Comment by chezzdev** [comment]
Done during moving AR to Native part.
