### ISSUE TITLE
AR lane improvement for ios

### ISSUE THREAD

**Issue by IodaMikeMapbox** [mapbox/mapbox-vision-ios#174]
## Description
Improvement should make lane adjustable to the environment which includes reflecting its color to shadows and detected objects based on segmentation mask, also it should make an impression like it's painted on the road.

Such improvement is already implemented on linux and almost on android.

## Goal
Improve ios AR lane.

## Steps
- [x] sync with @deniskoronchik;
- [x] implement;
- [ ] tested and acceptance criteria is matched (result matches the goal).

**Comment by IodaMikeMapbox** [comment]
- [ ] Move lane rendering to `MapboxVisionARNative`

**Comment by IodaMikeMapbox** [comment]
after discussion with @deniskoronchik decided to change api in accordance to the doc https://paper.dropbox.com/doc/VisionAR-view-refactoring--AjXhvVZB1XRrYpgD9vyJUnifAg-WQi1IUBNfMp5ca39oahPv

- [ ] change api

**Comment by chezzdev** [comment]
Closed with #206.
