### ISSUE TITLE
How to use your examples

### ISSUE THREAD

**Issue by ArtlyStyles** [mapbox/mapbox-vision-ios#176]
I am sorry, but I could not figure out how this vision SDK works. 

Your web site said: 

Download all Vision SDK components in a single zip file for either iOS 

For iOS, you will also need to include source files for MapboxVision frameworks in your project.

What does this mean? Why do I need source file after I already download your SDK?

And this repo has no README to explain how to add source file to my project.

**Comment by chezzdev** [comment]
Hello, @ArtlyStyles. Thanks for checking out `MapboxVision`.

There're two parts of Mapbox Vision SDK for iOS: "Native" part which provides core functionality and "Platform" part which provides necessary components for proper work with iOS and Swift.

At [vision.mapbox.com/install](https://vision.mapbox.com/install) we do mention an option to download Vision SDK directly. For that, you need to download a `zip` file with "Native" libraries as well as "Platform" code from this repository and include them into your project.

However, the recommended approach is to utilize one of the package managers: Carthage or CocoaPods. There are short instructions on how to do that in "Import Vision into your project with a package manager " section of [vision.mapbox.com/install](https://vision.mapbox.com/install). These guides will help you set up your project in several steps without the need to import libraries and code yourself.

Is this approach suits you?
