### ISSUE TITLE
Check the behaviour of clean method on RecordSyncronizer.swift and fix it if it’s needed

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-vision-ios#192]
## Description

`RecordSyncronizer.swift` contains method `clean()`. It should remove the oldest directories with recordings if they’re exceeding a disk quota (the newest (which one created recently) directories should be on disk if the quota allows).  

To determine the "oldest" dirs `clean()` method uses `sortedByCreationDate()` method (defined in `extension Array` in `URL.swift` file.). According to the implementation of extension seems it sorts dates in a such order that the oldest date will appear first, then the newest (the "bigger" one) appears.   It leads us to the case when `clean()` method “removes” (in its `reduce` section) not the "oldest" directories, but the newest (these which were added most recently). 

## Goal

To have a behavior that meets our expectations.

## Steps
- [ ] Check the behaviour and agree on how it should be .
- [ ] Fix it if it’s needed
- [ ] Document the behaviour 
- [ ] Add basic unit tests to prevent future issues

**Comment by chezzdev** [comment]
Not relevant due to internal changes of synchronization.
