### ISSUE TITLE
Crash when tearing down VisionReplayManager

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#217]
## Description
When I try and stop & tear down the VisionReplayManager, I get a crash in the destroy method for VisionReplayManager.

I believe it may be something similar to the issue addressed here: #130 

## Expected behavior
destroy() succeeds and we are able to create a new instance at a later time

## Actual behavior
Crash

## Configuration
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS11.2]
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.7.1]
   - MapboxVisionARNative [e.g. 0.7.1]
   - MapboxVisionSafetyNative [e.g. 0.7.1]

## Additional context
This is inside my branch of Apex that allows for replay of recorded vision sessions.

**Comment by chezzdev** [comment]
The issue was resolved and will be shipped in the next release.
