### ISSUE TITLE
No Blue Lane showing in AR Navigation

### ISSUE THREAD

**Issue by francorobles** [mapbox/mapbox-vision-ios#219]
## Description
No Blue Lane showing in AR Navigation

## Expected behavior
Blue Lane showing in AR Navigation

## Actual behavior
App is running but no blue lane is showing in AR Navigation

## Configuration
 - Device: iPhone6s Plus
 - OS: iOS12.4

**Comment by francorobles** [comment]
Tested in XS Max. Same behavior.

**Comment by francorobles** [comment]
Hi All,

Any feedback on this one?

**Comment by chezzdev** [comment]
Hey, @francorobles!
Could you please share more details about your setup? Namely, version of the SDK, modules that you’re using, how do you provide a route to the SDK and in what conditions do you perform testing (indoors / outdoors). Concerning the last point, AR functionality depends on the GPS accuracy, so the best conditions would be outdoors.

**Comment by francorobles** [comment]
> Hey, @francorobles!
> Could you please share more details about your setup? Namely, version of the SDK, modules that you’re using, how do you provide a route to the SDK and in what conditions do you perform testing (indoors / outdoors). Concerning the last point, AR functionality depends on the GPS accuracy, so the best conditions would be outdoors.

Hello @chezzdev 

I will send you the details tomorrow. In awhile. And thank you for attending to this.

Kind Regards,
Franco

**Comment by francorobles** [comment]
@chezzdev 2 of us are experiencing already. I tried again last weekend still experiencing the same. Any ideas? I was using version 0.8.1 of the libraries.

**Comment by chezzdev** [comment]
@francorobles @zhengzheng new version of `MapboxVision` 0.9.0 with the new AR experience has been released. Please check it out and see if the problem persists.
Also please make sure you're supplying a valid Mapbox token and test AR outside.
Please feel free to reopen this issue or open a new one with as many details of your workflow as possible if you encounter problems with AR again.

**Comment by francorobles** [comment]
@chezzdev will do. Hopefully the blue lane now shows up on this version. Will comment my findings soon.

**Comment by zhengzheng** [comment]
@chezzdev I trid the version 0.9.0. No Blue Lane on iPhone Xs Max(iOS 13.1), but It can be shown on iPhone 6s Plus. I'm sure my token is valid.

**Comment by francorobles** [comment]
@chezzdev Same here, tried on 0.9.0 on iPhone Xs Max(iOS 13.0), no blue lane.

**Comment by chezzdev** [comment]
Hey, @zhengzheng @francorobles. Do you test your apps outside / on the road? AR is sensitive to GPS accuracy, so it might not appear when testing inside. 

One other question is do you have AR working when running the [Teaser app](https://github.com/mapbox/vision-ios-examples) on the same devices?

**Comment by zhengzheng** [comment]
Hi, @chezzdev. YES, We test our app on the road. I will try the demo app tomorrow. We can provide the video for the issue, tomorrow.

**Comment by zhengzheng** [comment]
Hi, @chezzdev . We have recoding 3 videos.
1、iPhone 6s Plus - iOS 13.0 - https://youtu.be/S8Hlu9VAcXs
2、iPhone Xs Max - iOS 13.1 - https://youtu.be/HZIoqN57OJM
3、iPhone Xs Max - iOS 13.1 - https://youtu.be/DfO-uHNRPWU

**Comment by francorobles** [comment]
@zhengzheng may I know if you modified anything in the code?

**Comment by zhengzheng** [comment]
@francorobles No, I do NOT modify anything.

**Comment by lbrun25** [comment]
Hi, I confirm that because I have the same problem on Iphone 11 (IOS 13) when I test the example of ARNavigation, the blue line doesn't show.

**Comment by chezzdev** [comment]
Hey, everyone. Thanks for your patience.
This issue was fixed in `0.10.1` release of `MapboxVision`. Please update and see if your use-cases work.
