### ISSUE TITLE
VisionReplayManager should support seeking to a time in a recording

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#220]
## Description
Currently the VisionReplayManager only allows you to start playback of a recording from the beginning through to the end.

It would be very useful to be able to "seek" to a specific time in the recording and playback from there.

**Comment by chezzdev** [comment]
Hey @avi-c! We've implemented seeking in Vision 0.12.0. Use can use [`progress` property](https://docs.mapbox.com/ios/api/vision/vision/0.12.0/Classes/VisionReplayManager.html#/s:12MapboxVision0B13ReplayManagerC8progressSfvp) to achieve seek functionality.

Looking forward to your feedback!
