### ISSUE TITLE
Animation to MGLPointAnnotation from one coordinate to another

### ISSUE THREAD

**Issue by Rahulpatil710** [mapbox/mapbox-vision-ios#246]
## Description
I added one annotation on map using this class MGLPointAnnotation. Now i need to move this annotation as location change. Please let me know how can i do this ? I tried with by setting new coordinates to annotation but it is not working. Also I need to animate that annotation while it is moving so it will look like smooth movement. Any idea or suggestion please ?
## Expected behavior
Need to add animation to custom MGLPointAnnotation.

## Actual behavior
CATransaction is not applying to MGLPointAnnotation. 

## Configuration
 - Device: Any iPhone
 - OS: Above 12
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.3.0]
   - MapboxVisionARNative [e.g. 0.3.0]
   - MapboxVisionSafetyNative [e.g. 0.3.0]
   - MapboxVision [e.g. 0.3.0]
   - MapboxVisionAR [e.g. 0.3.0]
   - MapboxVisionSafetyNative [e.g. 0.3.0]

## Additional context
I added one annotation on map using this class MGLPointAnnotation. Now i need to move this annotation as location change. Please let me know how can i do this ? I tried with by setting new coordinates to annotation but it is not working.
Also I need to animate that annotation while it is moving so it will look like smooth movement. Any idea or suggestion please ?

**Comment by chezzdev** [comment]
Hey @Rahulpatil710, `MGLPointAnnotation` is a class from `Mapbox-iOS-SDK` which is hosted in https://github.com/mapbox/mapbox-gl-native repo. I guess you want to create an issue there.
