### ISSUE TITLE
VisionReplayManager.create always gives me an error

### ISSUE THREAD

**Issue by gariyanto** [mapbox/mapbox-vision-ios#249]
## Description
Got an error when running this command, although I already had a valid directory path with Mapbox recording data.

guard let visionReplayManager = try? VisionReplayManager.create(recordPath: path) else {
    fatalError("\(path) doesn't exist")
}

## Expected behavior
visionReplayManager should be created and ready to be used for testing.

## Actual behavior
Throw an exception complaining that the directory doesn't exist

## Configuration
 - Device: [e.g. iPhoneXS Max]
 - OS: [e.g. iOS13.1]
 - Frameworks versions (leave the ones you're using):
   - MapboxVisionNative [e.g. 0.10.0]
   - MapboxVisionARNative [e.g. 0.10.0]
   - MapboxVisionSafetyNative [e.g. 0.10.0]
   - MapboxVision [e.g. 0.10.0]
   - MapboxVisionAR [e.g. 0.10.0]
   - MapboxVisionSafetyNative [e.g. 0.10.0]

## Additional context
When running in the simulator, I can see the content of the directory with the recorded data below:
camera.bin			ml_errors.bin
config.bin			motion.bin
detections.bin			platform_performance.bin
device.bin			position.bin
fps_snapshots.bin		road_description.bin
frames.bin			signs.bin
gps.bin				vcore_statistics.bin
heading.bin			videos.json
images				vm_statistics.bin
mappings.bin			world_transform.bin

**Comment by chezzdev** [comment]
Hey @gariyanto. Could you please show how your `path` looks like? Also please elaborate on where the recorded session is stored. Is it a Documents dir, app bundle or something else?

**Comment by gariyanto** [comment]
> Hey @gariyanto. Could you please show how your `path` looks like? Also please elaborate on where the recorded session is stored. Is it a Documents dir, app bundle or something else?

I created the storage path as follows:
`let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)`
`let docDir = docs[0]`
`storagePath = docDir.path + "/Mapbox/1/"`

After recording the session, I tried to play it using VisionReplayManager but the error always happened.

**Comment by chezzdev** [comment]
Creating the path looks right. 

I looked at the file list you've provided and I can't find a `video.mp4` file in the list you've provided. This is required to replay the recorded video stream.

Did you use `startRecording` / `stopRecording` methods on `VisionManager` to record the session?

**Comment by gariyanto** [comment]
> Creating the path looks right.
> 
> I looked at the file list you've provided and I can't find a `video.mp4` file in the list you've provided. This is required to replay the recorded video stream.
> 
> Did you use `startRecording` / `stopRecording` methods on `VisionManager` to record the session?

Yes, I used `startRecording` / `stopRecording` methods on `VisionManager` as described in the documentation.

**Comment by xyzbilal** [comment]
I m trying to run Example project and I m getting same error. Nothing changed in code. any solution advised??

**Comment by xyzbilal** [comment]
> Hey @gariyanto. Could you please show how your `path` looks like? Also please elaborate on where the recorded session is stored. Is it a Documents dir, app bundle or something else?

here is the path


```
let documentsPath =
            NSSearchPathForDirectoriesInDomains(.documentDirectory,
                                                .userDomainMask,
                                                true).first!
```


        let path = documentsPath.appending("/safety-alerts-drawing")

**Comment by gariyanto** [comment]
> > Hey @gariyanto. Could you please show how your `path` looks like? Also please elaborate on where the recorded session is stored. Is it a Documents dir, app bundle or something else?
> 
> here is the path
> 
> ```
> let documentsPath =
>             NSSearchPathForDirectoriesInDomains(.documentDirectory,
>                                                 .userDomainMask,
>                                                 true).first!
> ```
> 
> ```
>     let path = documentsPath.appending("/safety-alerts-drawing")
> ```

Hi @xyzbilal, I've solved the problem. The problem was no video.mp4 saved into the directory. If you implement VisionManagerDelegate then you will be able to save the video.mp4 automatically and eventually you can replay the recorded data.

**Comment by chezzdev** [comment]
Hey @xyzbilal! If you're trying to run Safety Alerts example, please follow the steps in [Getting started](https://docs.mapbox.com/help/tutorials/ios-vision-safety-alerts/#getting-started) section of the corresponding tutorial.
You'll need to download a session and upload it to the app so that it could be replayed.
Please write back if you have any difficulties.

**Comment by xyzbilal** [comment]
@chezzdev , @gariyanto thank you very much  for valuable replies. I will consider what you suggest. thanks.

**Comment by chezzdev** [comment]
@gariyanto please try to record the sessions with the latest version of the framework: we've fixed a couple of issues with the file system, so video file should be saved more consistently.

**Comment by chezzdev** [comment]
Considering as solved. Please reopen the issue if you still see the problem.
