### ISSUE TITLE
Update MapboxMobileEvents to v0.10.2

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#273]
Merge in support for MapboxMobileEvents v0.10.2 so we can update Apex to Vision v0.11.0

**Comment by chezzdev** [comment]
@avi-c I've created a branch from `master` that provides basic integration of `MapboxMobileEvents` v0.10.2. Proper integration will come in `MapboxVision` v0.11.0 and can be tracked here https://github.com/mapbox/mapbox-vision/issues/2086.
