### ISSUE TITLE
Vision SDK pods problem

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-vision-ios#275]
## Description

I follow mapbox guide for installing Vision SDK but I get error when installing pods
## Goal

To add VISION SDK features to my app

## Steps

I have in pod file:
platform :ios, '11.2'

pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.11.0.podspec?access_token=my generated token with vision download scope'

# Vision only
pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.11.0'

# AR
pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.11.0'

# Safety
pod "MapboxVisionSafety", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.11.0'

In attach picture you can see error, I try to set iOS 13 but still I get this error
<img width="682" alt="Screenshot 2020-02-29 at 15 32 35" src="https://user-images.githubusercontent.com/4254736/75609470-201fa700-5b09-11ea-901c-8bba549fb18a.png">

**Comment by chezzdev** [comment]
Hey, @nole87. Could you please try `pod update`? Seems like there is some problem with your `Podfile.lock` file.

**Comment by nole87** [comment]
With pod update I get this error

<img width="682" alt="Screenshot 2020-03-03 at 07 07 22" src="https://user-images.githubusercontent.com/4254736/75747598-a7ddff00-5d1d-11ea-9701-ae026acacd39.png">

**Comment by chezzdev** [comment]
I see. This is a known version conflict which should be resolved in the next version of Vision. Meanwhile you can specify v5.5.1 for Maps to avoid the conflict.

**Comment by nole87** [comment]
Be quick with new version of Vision SDK :)
