### ISSUE TITLE
xcode target deployment bug with vision sdk

### ISSUE THREAD

**Issue by nole87** [mapbox/mapbox-vision-ios#276]
## Description
I set deployment target to 11.2, also in pod file 11.2 but when trying to compile I get error: Compiling for iOS 9.0, but module 'MapboxVision' has a minimum deployment target of iOS 11.2: /Users/kacerac/Library/Developer/Xcode/DerivedData/Patroler-fslhnlcuwhtgggarlengwvecqrua/Build/Products/Debug-iphoneos/MapboxVision/MapboxVision.framework/Modules/MapboxVision.swiftmodule/arm64-apple-ios.swiftmodule

## Goal
Add Vision features to my app

## Steps

![1](https://user-images.githubusercontent.com/4254736/75797353-56615e80-5d75-11ea-967f-357b874e9ec9.jpg)
![2](https://user-images.githubusercontent.com/4254736/75797367-59f4e580-5d75-11ea-9e2e-52f8a41d02a0.jpg)

**Comment by chezzdev** [comment]
Hey, @nole87. This is probably not Vision-related, but my guess is that you have different deployment targets for project and target levels. Check if your target has a deployment target of iOS 11.2 or later.

**Comment by nole87** [comment]
iOS development target was 9.0 under project target
