### ISSUE TITLE
Dependency on MapboxAccounts v2.1.0 prevents Apex update to Nav Native v14 and up

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-vision-ios#313]
As part of keeping up to date on the Mapbox Navigation SDK Apex inherits a dependency on MapboxAccounts v2.2.0 or higher.

This is incompatible with the version of MapboxVision used in Apex. We are currently using the following CocoaPods dependencies:

pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.12.0.podspec?access_token=OUR_SECRET_TOKEN'
    # Vision only
    pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :branch => 'pad-telemetry-0.10.2-vision-0.12.0'
    # AR
    pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :branch => 'release/0.12.0'

In order to maintain support for Vision inside of Apex we need it to move to a newer accounts framework, at least in our private branch of Vision

**Comment by avi-c** [comment]
The part I can't work around is the dependency specified in the private MapboxVisionNative podspec: https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.12.0.podspec

**Comment by avi-c** [comment]
@alexshalamov @chezzdev - I know iOS is low priority now, but is it possible to investigate if this is a simple change? I'm hoping that MapboxAccounts v2.2.0 doesn't have any breaking changes so the extent of the fix would be to change the dependency.

**Comment by chezzdev** [comment]
@avi-c thanks for posting this. Dependency will be updated in Vision 0.13.0, which is scheduled to be released by 07/30.
