### ISSUE TITLE
Unable to import MapboxVision classes into Objective C project

### ISSUE THREAD

**Issue by billylo1** [mapbox/mapbox-vision-ios#324]
After adding the required Pods, I added this import to my existing objective c code to add mapbox vision functionality

`#import <MapboxVision/MapboxVision-Swift.h>
`

But Xcode can't find the Mapbox classes.  I have used the same approach to import classes from other Swift based frameworks.  Am I missing something?  Podfile has use_framework! as well.

thanks.

```
pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.13.0.podspec?access_token=mytoken'
pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
pod "MapboxVisionSafety", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
```

**Comment by chezzdev** [comment]
Hey @billylo1, `MapboxVision` only supports Swift. You can still use `MapboxVision` from the Swift code in your project.

**Comment by changpk** [comment]
> Hey @billylo1, `MapboxVision` only supports Swift. You can still use `MapboxVision` from the Swift code in your project.

That is to say, the related functions of Mapbox Vision cannot be used in OC's project projects

**Comment by changpk** [comment]
> After adding the required Pods, I added this import to my existing objective c code to add mapbox vision functionality
> 
> `#import <MapboxVision/MapboxVision-Swift.h> `
> 
> But Xcode can't find the Mapbox classes. I have used the same approach to import classes from other Swift based frameworks. Am I missing something? Podfile has use_framework! as well.
> 
> thanks.
> 
> ```
> pod 'MapboxVisionNativeAll', :podspec => 'https://api.mapbox.com/downloads/v1/vision/ios/mapbox-vision-native-all/0.13.0.podspec?access_token=mytoken'
> pod "MapboxVision", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
> pod "MapboxVisionAR", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
> pod "MapboxVisionSafety", :git => 'https://github.com/mapbox/mapbox-vision-ios.git', :tag => 'v0.13.0'
> ```

That is to say, the related functions of Mapbox Vision cannot be used in OC's project?

**Comment by billylo1** [comment]
I managed to get it to work by adding an extra Swift class to act as a bridge.  (communications both ways, to/from ObjC classes.
