### ISSUE TITLE
Looking for support of portrait mode 

### ISSUE THREAD

**Issue by billylo1** [mapbox/mapbox-vision-ios#330]
## Description
Currently, VisionManager works in landscape mode only.  Sign detection does not work well in portrait.

## Expected behavior
Support for portrait mode

## Configuration
 - Device: iPhone 11
 - OS: iOS 13.6

## Additional context
any hints to make it work in portrait mode?

**Comment by billylo1** [comment]
It does work in portrait mode... I was mistaken.  Sorry about the confusion.

**Comment by csongorkeller** [comment]
@billylo1 How did you manage to launch in portrait mode? Could you share the know-how?
Thanks

**Comment by billylo1** [comment]
Are you referring to the sample app? In my own app (Sidekick-app.com), I have the code below to set up the preview layer. Nothing special required on the Mapbox Vision SDK side of things.

```
AVCaptureVideoPreviewLayer *previewLayer = (AVCaptureVideoPreviewLayer *)self.previewView.layer;
previewLayer.connection.videoOrientation = initialVideoOrientation;
```
