### ISSUE TITLE
Swift 4.2 / 5 support

### ISSUE THREAD

**Issue by chezzdev** [mapbox/mapbox-vision-ios#83]
## Description

Currently supported Swift version is 4.1.

## Goal

Support contemporary version of swift (4.2 / 5)

## Steps

- [x] Research Swift 5 compatibility
- [x] Move to chosen (4.2 or 5) version of Swift

**Comment by chezzdev** [comment]
Migration to Swift 5 comes down to whether all of our clients are using Xcode 10.2 or not.
I think we don't need to rely on this assumption since the version is pretty new.
Thereby let's migrate to Swift 4.2.

**Comment by IodaMikeMapbox** [comment]
The changes should be done to repos:
- [ ] mapbox-vision-ios
- [ ] vision-ios-examples

**Comment by chezzdev** [comment]
Resolved in https://github.com/mapbox/mapbox-vision-ios/pull/85 and https://github.com/mapbox/vision-ios-examples/pull/61
