### ISSUE TITLE
Run models on iPhone Xr/Xs/Xs Max with higher FPS

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-vision-ios#87]
## Description
Currently we have implementation of `DeviceChecker.isTopDevice` method which tells us if the current iOS device has high performance capabilities. Initially it was implement to return `true` in case the current device is `iPhone10,` model (`iPhone 8/8 Plus/X`).

As we have new models `iPhon11,x` with `A12 Bionic SoC`, we should consider them as high performance devices as well. Otherwise we might face under-utilization of resources.

**NOTE:** Before merging we should check if the temperature is within acceptable parameters during operation mode.

  ## Goal
Update implementation of `DeviceChecker.isTopDevice` method in order to return `true` if the current device is `iPhone10,`+ model (including working on `A12 Bionic SoC`: `iPhone Xr/Xs/Xs Max`.

It will allow to utilize resources of new chip and give us more smoothly performance on the latest iPhone models.

  ## Steps
 - [x] Update implementation.
 - [x] Write basic unit tests.
 - [ ] Test that there's no FPS drop.

**Comment by chezzdev** [comment]
Why the task is closed? It's not merged yet.
