### ISSUE TITLE
Fix tests on iOS platform

### ISSUE THREAD

**Issue by dersim-davaod** [mapbox/mapbox-vision-ios#89]
## Description
Some tests were not updated in time as implementation changed.
Currently the following test targets were affected:
- MapboxVisionTests 
- demoTests

## Goal
The goal to allow run unit tests from targets above.

## Steps
- [x] Update MapboxVisionTests
- [ ] Update demoTests (separate repo)
- [ ] Update PR template to include `run tests locally` phase
- [ ] Tested and acceptance criteria is matched (result matches the goal)
- [ ] Provide configuration to run unit tests with CI server (as a part PR probably)

**Comment by vladzima** [comment]
Sprint?
